version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    user: "1000:1000"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    networks:
      - monitor-net
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    mem_limit: 1024m
    cpus: 0.5


networks:
  monitor-net:
    external:
      name: monitor-net
  
volumes:
  prometheus_data:
    external: 
      name: prometheus_data
