version: '3.7'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.6
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-polystat-panel,natel-plotly-panel, ae3e-plotly-panel, grafana-worldmap-panel, vonage-status-panel 
      

    networks:
      - monitor-net
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    mem_limit: 1024m
    cpus: 0.5


networks:
  monitor-net:
    external:
      name: monitor-net
  
volumes:
  grafana_data:
    external: 
      name: grafana_data