version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: postgres11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-net

volumes:
  postgres_data:
    external: false

networks:
  internal-net:
    external:
      name: docker-network-0
